

try{
    hello();
}catch(error){
    console.log(error);
}

try{
    anotherfun();
}catch{
    console.log("ocurrio un error");
}
